#!/bin/bash

####
# iptrules
####

####
# Global variable
DIRSTOR="/usr/local/iptreport"
FREPORT="ipt_report`date '+%d%m%Y%H%M'`"
ANLOG="anlog.awk"
IPTLOG="/var/log/iptables.log"

####
# Function
error() {
	echo $* >&2
	exit 1
}

syntax() {
	echo "Usage : ${0##*/} [-d <day>]"
	echo "<day> can be 1 or more day of the month. "
	echo "Eg : 12   will be the 12th day of the month"
}

#############################################################################
################      STARTING PROGRAM

test -d $DIRSTOR || mkdir $DIRSTOR

if [[ $# -gt 2 || $# -eq 1 ]]; then
	syntax
	exit 1
elif [[ $# -eq 2 && $1 != -[a-z] ]]; then
	syntax
	exit 1
fi

while getopts ":d:" option
do
	case "$option" in
		d)
			nbday=$OPTARG
			;;
		:)
			error "Need an argument for -$OPTARG"
			;;
		\?)
			error "INVALID OPTION"
			;;
	esac
done

if test $nbday; then
	if `echo $nbday |egrep -q "^[0-9]{1,}$"`; then
		if [[ $nbday -lt 1 || $nbday -gt 31 ]];then
			error "<day> out of interval"
		fi
	
		awk -f $ANLOG $nbday $DIRSTOR/$FREPORT $IPTLOG
	else
		error "Syntax error for the <day> argument"
	fi
else
	awk -f $ANLOG $DIRSTOR/$FREPORT $IPTLOG
fi
		
exit 0
